const swaggerAutogen = require('swagger-autogen')({ openapi: '3.0.0' });

const doc = {
  info: {
    version: '3.0.0',
    title: 'Question-assignments API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b>.',
  },
  host: 'localhost:8080',
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Question Assignment',
      description: 'Endpoints',
    },
  ],
  schemes: ['http'],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
      },
    },
    schemas: {
      UserSignupSchema: {
        $firstName: 'John',
        $lastName: 'Doe',
        $email: 'john.doe@gmail.com',
        $password: 'John@123456',
        $gender: 'male',
      },
      UserSignInSchema: {
        $email: 'john.doe@gmail.com',
        $password: 'John@123456',
      },
    },
  },
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/app.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
